export default {
    namespaced: true,//开启命名空间
    state: {
        cartList:[
            {   
                id:1,
                name:'111111',
                describe:'222222222',
                price:333,
                img:require('@/assets/img.jpg'),
                totalNum:1
            },{
                id:2,
                name:'aaaaaa',
                describe:'bbbbbb',
                price:1001,
                img:require('@/assets/img.jpg'),
                totalNum:2
            },{
                id:3,
                name:'qqqqqqq',
                describe:'wwwwww',
                price:2002,
                img:require('@/assets/img.jpg'),
                totalNum:3
            },{
                id:4,
                name:'ooooooo',
                describe:'pppppp',
                price:3003,
                img:require('@/assets/img.jpg'),
                totalNum:4
            },{
                id:5,
                name:'uuuuu',
                describe:'iiiiiii',
                price:4004,
                img:require('@/assets/img.jpg'),
                totalNum:4
            },{
                id:6,
                name:'aaaaaa',
                describe:'zzzzzz',
                price:5005,
                img:require('@/assets/img.jpg'),
                totalNum:4
            },{
                id:7,
                name:'xxxxx',
                describe:'dddddd',
                price:77777,
                img:require('@/assets/img.jpg'),
                totalNum:4
            },{
                id:8,
                name:'mmmmmm',
                describe:'nnnnnnnn',
                price:8888,
                img:require('@/assets/img.jpg'),
                totalNum:4
            },{
                id:9,
                name:'vvvvvv',
                describe:'bbbbbb',
                price:9999,
                img:require('@/assets/img.jpg'),
                totalNum:4
            },{
                id:10,
                name:'ccccc',
                describe:'dddddd',
                price:1010,
                img:require('@/assets/img.jpg'),
                totalNum:4
            },{
                id:11,
                name:'aaaaaa',
                describe:'bbbbbb',
                price:111111,
                img:require('@/assets/img.jpg'),
                totalNum:4
            },{
                id:12,
                name:'gggggg',
                describe:'tttttt',
                price:121212,
                img:require('@/assets/img.jpg'),
                totalNum:4
            },{
                id:13,
                name:'ffffff',
                describe:'eeeeeeee',
                price:131313,
                img:require('@/assets/img.jpg'),
                totalNum:4
            }]
    },
    mutations: {
        setShopCart(state,value){
            state.cartList = value
        }
    },
    actions: {
    },
    getters: {
    }
}
