server:
  port: 8182

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nft_db?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Zzy190015
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    com.nft: debug
  file:
    path: log/blog-dev.log

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com/nft/mapper/xml/**.xml
  type-aliases-package: com.nft.entity
#  global-config:
#    db-config:
#      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以不加步骤2的注解)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

File:
  basePath: /Users/mac/IdeaProjects/nft/picture
